SafeCamProject/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SafeCamProject.Models;

namespace SafeCamProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SafeCamProject/ViewComponents/AboutViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SafeCamProject.ViewComponents
{
    public class AboutViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

SafeCamProject/ViewComponents/CarouselViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SafeCamProject.ViewComponents
{
    public class CarouselViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

SafeCamProject/ViewComponents/PricingViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SafeCamProject.ViewComponents
{
    public class PricingViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

SafeCamProject/ViewComponents/TeamViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SafeCamProject.Services.Interfaces;
using SafeCamProject.ViewsModel;

namespace SafeCamProject.ViewComponents
{
    public class TeamViewComponent : ViewComponent
    {
        private readonly IProfessionService _professionService;
        private readonly ITeamService _teamService;
        public TeamViewComponent(IProfessionService professionService , ITeamService teamService)
        {
            _professionService = professionService;
            _teamService = teamService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var teams = await _teamService.GetAllAsync();
            
            return View(teams);
        }
    }
}

SafeCamProject/Views/Home/Index.cshtml
<!-- Carousel Start -->
@await Component.InvokeAsync("Carousel")
<!-- Carousel End -->
<!-- About Start -->
@await Component.InvokeAsync("About")
<!-- About End -->
<!-- Services Start -->
@await Component.InvokeAsync("Services")

<!-- Services End -->
<!-- Pricing Plan Start -->
@await Component.InvokeAsync("Pricing")

<!-- Pricing Plan End -->
<!-- Offer Start -->
<div class="container-fluid bg-offer my-5 py-5 wow zoomIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-7 text-center">
                <div class="text-center mx-auto mb-4" style="max-width: 600px;">
                    <h5 class="text-white text-uppercase" style="letter-spacing: 5px;">Special Offer</h5>
                    <h1 class="display-5 text-white">Save 50% On All Items Your First Order</h1>
                </div>
                <p class="text-white mb-4">Eirmod sed tempor lorem ut dolores sit kasd ipsum. Dolor ea et dolore et at sea ea at dolor justo ipsum duo rebum sea. Eos vero eos vero ea et dolore eirmod et. Dolores diam duo lorem. Elitr ut dolores magna sit. Sea dolore sed et.</p>
                <a href="" class="btn btn-primary py-md-3 px-md-5 me-3">Order Now</a>
                <a href="" class="btn btn-secondary py-md-3 px-md-5">Read More</a>
            </div>
        </div>
    </div>
</div>
<!-- Offer End -->

<!-- Team Start -->
@await Component.InvokeAsync("Team")
<!-- Team End -->

<!-- Testimonial Start -->
<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="text-center mx-auto mb-5" style="max-width: 600px;">
            <h5 class="text-primary text-uppercase" style="letter-spacing: 5px;">Testimonial</h5>
            <h1 class="display-5 mb-0">What People Say About Our Services</h1>
        </div>
        <div class="owl-carousel testimonial-carousel">
            <div class="text-center pb-4">
                <img class="img-fluid mx-auto rounded-circle" src="~/assets/img/testimonial-1.jpg" style="width: 100px; height: 100px;">
                <div class="testimonial-text bg-light rounded p-4 mt-n5">
                    <p class="mt-5">
                        Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam
                    </p>
                    <h4 class="text-truncate">Client Name</h4>
                    <i>Profession</i>
                </div>
            </div>
            <div class="text-center">
                <img class="img-fluid mx-auto rounded-circle" src="~/assets/img/testimonial-2.jpg" style="width: 100px; height: 100px;">
                <div class="testimonial-text bg-light rounded p-4 mt-n5">
                    <p class="mt-5">
                        Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam
                    </p>
                    <h4 class="text-truncate">Client Name</h4>
                    <i>Profession</i>
                </div>
            </div>
            <div class="text-center">
                <img class="img-fluid mx-auto rounded-circle" src="~/assets/img/testimonial-3.jpg" style="width: 100px; height: 100px;">
                <div class="testimonial-text bg-light rounded p-4 mt-n5">
                    <p class="mt-5">
                        Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam
                    </p>
                    <h4 class="text-truncate">Client Name</h4>
                    <i>Profession</i>
                </div>
            </div>
            <div class="text-center">
                <img class="img-fluid mx-auto rounded-circle" src="~/assets/img/testimonial-4.jpg" style="width: 100px; height: 100px;">
                <div class="testimonial-text bg-light rounded p-4 mt-n5">
                    <p class="mt-5">
                        Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam
                    </p>
                    <h4 class="text-truncate">Client Name</h4>
                    <i>Profession</i>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial End -->
<!-- Blog Start -->
<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="text-center mx-auto mb-5" style="max-width: 600px;">
            <h5 class="text-primary text-uppercase" style="letter-spacing: 5px;">Blog Post</h5>
            <h1 class="display-5 mb-0">Latest Articles From Our Blog Post</h1>
        </div>
        <div class="row g-5">
            <div class="col-lg-6 wow slideInUp" data-wow-delay="0.3s">
                <div class="blog-item">
                    <div class="position-relative">
                        <img class="img-fluid w-100 rounded-top" src="~/assets/img/blog-1.jpg" alt="">
                        <div class="blog-date">
                            <h5 class="text-white fw-bold mb-0">01</h5>
                            <h6 class="text-light mb-0">January</h6>
                        </div>
                    </div>
                    <div class="bg-primary rounded-bottom p-5">
                        <div class="d-flex mb-3">
                            <span class="text-light text-uppercase">Admin</span>
                            <span class="text-light px-2">|</span>
                            <span class="text-light text-uppercase">Web Design</span>
                        </div>
                        <a class="h3 m-0 text-white" href="">Kasd dolor lorem sit justo rebum stet justo elitr dolor amet sit</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 wow slideInUp" data-wow-delay="0.6s">
                <div class="blog-item">
                    <div class="position-relative">
                        <img class="img-fluid w-100 rounded-top" src="~/assets/img/blog-2.jpg" alt="">
                        <div class="blog-date">
                            <h5 class="text-white fw-bold mb-0">01</h5>
                            <h6 class="text-light mb-0">January</h6>
                        </div>
                    </div>
                    <div class="bg-primary rounded-bottom p-5">
                        <div class="d-flex mb-3">
                            <span class="text-light text-uppercase">Admin</span>
                            <span class="text-light px-2">|</span>
                            <span class="text-light text-uppercase">Web Design</span>
                        </div>
                        <a class="h3 m-0 text-white" href="">Kasd dolor lorem sit justo rebum stet justo elitr dolor amet sit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Blog End -->