SafeCamProject/Models/Team.cs
using System.ComponentModel.DataAnnotations;

namespace SafeCamProject.Models
{
    public class Team : BaseEntity
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Image { get; set; }
        public int ProfessionId { get; set; }
        public Profession Profession { get; set; }
    }
}

SafeCamProject/Areas/Admin/Controllers/ProfessionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SafeCamProject.Services.Interfaces;
using SafeCamProject.ViewsModel.Profession;

namespace SafeCamProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProfessionController : Controller
    {
        private readonly IProfessionService _professionService;
        public ProfessionController(IProfessionService professionService)
        {
            _professionService = professionService;
        }
        public async Task<IActionResult> Index()
        {
            var professions = await _professionService.GetAllAdminAsync();
            return View(professions);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            if (id == null) return BadRequest();
            var profession = await _professionService.GetByIdAsync(id);
            if (profession == null) return NotFound();
            return View(profession);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProfessionCreateVM professionCreateVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _professionService.CreateAsync(professionCreateVM);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _professionService.GetByIdAsync(id.Value);
            if (data == null) return NotFound();

            await _professionService.DeleteAsync(data.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _professionService.GetByIdAsync(id.Value);
            if (data == null) return NotFound();

            return View(new ProfessionUpdateVM
            {
                Id = data.Id,
                Name = data.Name
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(int? id, ProfessionUpdateVM professionUpdateVM)
        {
            if(!ModelState.IsValid) return BadRequest();
            if (id == null) return BadRequest();
            var data = await _professionService.GetByIdAsync(id.Value);
            if (data == null) return NotFound();

            await _professionService.UpdateAsync(data.Id, professionUpdateVM);
            return RedirectToAction("Index");
        }
    }
}

SafeCamProject/Areas/Admin/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using SafeCamProject.Services;
using SafeCamProject.Services.Interfaces;
using SafeCamProject.ViewsModel.Profession;
using SafeCamProject.ViewsModel.Team;

namespace SafeCamProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeamController : Controller
    {
        private readonly ITeamService _teamService;
        private readonly IProfessionService _professionService;
        public TeamController(ITeamService teamService, IProfessionService professionService)
        {
            _teamService = teamService;
            _professionService = professionService;
        }
        public async Task<IActionResult> Index()
        {
            var teams = await _teamService.GetAllAdminAsync();
            return View(teams);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            if (id == null) return BadRequest();
            var team = await _teamService.GetByIdAsync(id);
            if (team == null) return NotFound();
            return View(team);
        }



        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Professions = await _professionService.GetAllSelectedAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TeamCreateVM teamCreateVM)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Professions = await _professionService.GetAllSelectedAsync();
                return View(teamCreateVM);
            }
            await _teamService.CreateAsync(teamCreateVM);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _teamService.GetByIdAsync(id.Value);
            if (data == null) return NotFound();

            await _teamService.DeleteASync(data.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _teamService.GetByIdAsync(id.Value);
            if (data == null) return NotFound();

            ViewBag.Professions = await _professionService.GetAllSelectedAsync();

            return View(new TeamUpdateVM
            {
                Id = data.Id,
                Name = data.Name,
                ProfessionId = data.ProfessionId
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(int? id, TeamUpdateVM teamUpdateVM)
        {
            if (id == null) return BadRequest();

            if (!ModelState.IsValid)
            {
                ViewBag.Professions = await _professionService.GetAllSelectedAsync();
                return View(teamUpdateVM);
            }

            var data = await _teamService.GetByIdAsync(id.Value);
            if (data == null) return NotFound();

            await _teamService.UpdateAsync(data.Id, teamUpdateVM);
            return RedirectToAction("Index");
        }
    }
}

SafeCamProject/Areas/Admin/Views/Team/Create.cshtml
@model TeamCreateVM

<div class="body-wrapper-inner">
    <div class="container-fluid">
        <!--  Row 1 -->
        <div class="row">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Name</label>
                    <input asp-for="Name" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <span asp-validation-for="Name"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Profession</label>
                    <select asp-for="ProfessionId" asp-items="@ViewBag.Professions" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"></select>
                    <span asp-validation-for="ProfessionId"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Image</label>
                    <input asp-for="Image" type="file" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <span asp-validation-for="Image"></span>
                </div>
                <button asp-action="Create" type="submit" class="btn btn-primary">Create</button>
                <a class="btn btn-warning" asp-controller="Profession" asp-action="Index">Back</a>
            </form>

        </div>
    </div>
</div>

SafeCamProject/Areas/Admin/Views/Team/Detail.cshtml
@model TeamDetailVM
<div class="body-wrapper-inner">
    <div class="container-fluid">
        <!--  Row 1 -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <div>
                                <h4 class="card-title">Products Performance</h4>
                                <p class="card-subtitle">
                                    Ample Admin Vs Pixel Admin
                                </p>
                            </div>
                            <div class="ms-auto mt-3 mt-md-0">
                                <select class="form-select theme-select border-0" aria-label="Default select example">
                                    <option value="1">March 2025</option>
                                    <option value="2">March 2025</option>
                                    <option value="3">March 2025</option>
                                </select>
                            </div>
                        </div>
                        <div class="table-responsive mt-4">
                            <table class="table mb-0 text-nowrap varient-table align-middle fs-3">
                                <thead>
                                    <tr>
                                        <th scope="col" class="px-0 text-muted">
                                            Id
                                        </th>
                                        <th scope="col" class="px-0 text-muted">Image</th>
                                        <th scope="col" class="px-0 text-muted">Name</th>
                                        <th scope="col" class="px-0 text-muted">
                                            Profession Name
                                        </th>
                                        <th scope="col" class="px-0 text-muted">
                                            Profession Id
                                        </th>
                                        <th scope="col" class="px-0 text-muted">CreateDate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <tr>
                                            <td class="px-0">@Model.Id</td>
                                            <td class="px-0">
                                                <div class="d-flex align-items-center">
                                                    <img src="~/assets/img/@Model.Image" class="rounded-circle" width="200"
                                                         alt="flexy" />
                                                    <div class="ms-3">
                                                        <h6 class="mb-0 fw-bolder">@Model.Image</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="px-0">@Model.Name</td>

                                            <td class="px-0">
                                                @Model.Profession
                                            </td>
                                        <td class="px-0">
                                            @Model.ProfessionId
                                        </td>

                                            <td class="px-0">
                                                @Model.CreateDate
                                            </td>

                                        </tr>
                                    
                                </tbody>
                            </table>
                            <a asp-action="Index" class="btn btn-warning">Back</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SafeCamProject/Areas/Admin/Views/Team/Index.cshtml
@model IEnumerable<TeamVM>
<div class="body-wrapper-inner">
    <div class="container-fluid">
        <!--  Row 1 -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <div>
                                <h4 class="card-title">Products Performance</h4>
                                <p class="card-subtitle">
                                    Ample Admin Vs Pixel Admin
                                </p>
                            </div>
                            <div class="ms-auto mt-3 mt-md-0">
                                <a class="btn btn-success" asp-controller="Team" asp-action="Create">Create</a>
                            </div>
                        </div>
                        <div class="table-responsive mt-4">
                            <table class="table mb-0 text-nowrap varient-table align-middle fs-3">
                                <thead>
                                    <tr>
                                        <th scope="col" class="px-0 text-muted">
                                            Id
                                        </th>
                                        <th scope="col" class="px-0 text-muted">Image</th>
                                        <th scope="col" class="px-0 text-muted">Name</th>
                                        <th scope="col" class="px-0 text-muted">
                                            Profession Name
                                        </th>
                                        <th scope="col" class="px-0 text-muted">CreateDate</th>
                                        <th scope="col" class="px-0 text-muted text-end">
                                            Operations
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="px-0">@item.Id</td>
                                            <td class="px-0">
                                                <div class="d-flex align-items-center">
                                                    <img src="~/assets/img/@item.Image" class="rounded-circle" width="40"
                                                    alt="flexy" />
                                                    <div class="ms-3">
                                                        <h6 class="mb-0 fw-bolder">@item.Image</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="px-0">@item.Name</td>
                                            
                                            <td class="px-0">
                                                @item.Profession
                                            </td>

                                            <td class="px-0">
                                                @item.CreateDate
                                            </td>

                                            <td class="px-0 text-dark fw-medium text-end">
                                                <a asp-controller="Team" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-info">View</a>
                                                <a asp-controller="Team" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Update</a>
                                                <form method="post" style="display:inline">
                                                    <button asp-controller ="Team" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</button>
                                                </form>
                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SafeCamProject/Areas/Admin/Views/Team/Update.cshtml
@model TeamUpdateVM

<div class="body-wrapper-inner">
    <div class="container-fluid">
        <!--  Row 1 -->
        <div class="row">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Name</label>
                    <input asp-for="Name" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <span asp-validation-for="Name"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Profession</label>
                    <select asp-for="ProfessionId" asp-items="@ViewBag.Professions" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"></select>
                    <span asp-validation-for="ProfessionId"></span>
                </div>
                <div class="mb-3">
                    <label for="ImageInput" class="form-label">Image</label>
                    <input asp-for="Image" id="ImageInput" type="file" class="form-control" aria-describedby="emailHelp" accept="image/*">
                    <span asp-validation-for="Image"></span>
                    
                </div>
                
                <button asp-action="Update" type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-warning" asp-controller="Team" asp-action="Index">Back</a>
            </form>

        </div>
    </div>
</div>